# Generated by Django 4.2.6 on 2023-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=5),
        ),
    ]
